src/DevMS.App/ViewModels/ProdutoViewModel.cs
using DevMS.App.Extensions;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DevMS.App.ViewModels
{
    public class ProdutoViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Fornecedor")]
        public Guid FornecedorId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(200, ErrorMessage = "O campo {0} deve ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Nome { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(1000, ErrorMessage = "O campo {0} deve ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Descricao { get; set; }

        [DisplayName("Imagem do Produto")]
        public IFormFile ImagemUpload{ get; set; }
        public string Imagem { get; set; }

        [Moeda]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public decimal Valor { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DataCadastro { get; set; }

        [DisplayName("Ativo?")]
        public bool Ativo { get; set; }

        public FornecedorViewModel Fornecedor { get; set; }
        public IEnumerable<FornecedorViewModel> Fornecedores { get; set; }
    }
}

src/DevMS.App/Controllers/ProdutosController.cs
using AutoMapper;
using DevMS.App.Extensions;
using DevMS.App.ViewModels;
using DevMS.Business.Interfaces;
using DevMS.Business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DevMS.App.Controllers
{
    [Authorize]
    public class ProdutosController : BaseController
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly IFornecedorRepository _fornecedorRepository;
        private readonly IProdutoService _produtoService;
        private readonly IMapper _mapper;
        private readonly ILogger<ProdutosController> _logger;

        public ProdutosController(IProdutoRepository produtoRepository,
                                  IMapper mapper,
                                  IFornecedorRepository fornecedorRepository,
                                  IProdutoService produtoService,
                                  ILogger<ProdutosController> logger,
                                  INotificador notificador) : base(notificador)
        {
            _produtoRepository = produtoRepository;
            _fornecedorRepository = fornecedorRepository;
            _mapper = mapper;
            _logger = logger;
            _produtoService = produtoService;
        }

        [AllowAnonymous]
        [Route("listar-produtos")]
        public async Task<IActionResult> Index()
        {
            _logger.LogTrace("index-produto");

            return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(await _produtoRepository.ObterProdutosFornecedores()));
        }

        [AllowAnonymous]
        [Route("detalhes-produto/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var produtoViewModel = await ObterProduto(id);

            if(produtoViewModel == null)
                return NotFound();

            return View(produtoViewModel);
        }

        [ClaimsAuthorize("Produto","Adicionar")]
        [Route("novo-produto")]
        public async Task<IActionResult> Create()
        {
            var produtoViewModel = await PopularFornecedores(new ProdutoViewModel());
            return View(produtoViewModel);
        }

        [ClaimsAuthorize("Produto", "Adicionar")]
        [Route("novo-produto")]
        [HttpPost]
        public async Task<IActionResult> Create(ProdutoViewModel produtoViewModel)
        {
            produtoViewModel = await PopularFornecedores(produtoViewModel);

            if(!ModelState.IsValid)
                return View(produtoViewModel);

            var prefixo = Guid.NewGuid().ToString() + "_";

            if(! await UploadImagem(produtoViewModel.ImagemUpload, prefixo))
            {
                return View(produtoViewModel);
            }

            produtoViewModel.Imagem = $"{prefixo}{produtoViewModel.ImagemUpload.FileName}";
            await _produtoService.Adicionar(_mapper.Map<Produto>(produtoViewModel));

            if(!OperacaoValida()) return View(produtoViewModel);

            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Produto", "Editar")]
        [Route("editar-produto/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var produtoViewModel = await ObterProduto(id);

            if(produtoViewModel == null)
            {
                return NotFound();
            }

            return View(produtoViewModel);
        }

        [ClaimsAuthorize("Produto", "Editar")]
        [Route("editar-produto/{id:guid}")]
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, ProdutoViewModel produtoViewModel)
        {
            if(id != produtoViewModel.Id)
                return NotFound();

            var produtoAtualizacao = await ObterProduto(id);
            produtoViewModel.Fornecedor = produtoAtualizacao.Fornecedor;
            produtoViewModel.Imagem = produtoAtualizacao.Imagem;

            if(!ModelState.IsValid)
                return View(produtoViewModel);

            if(produtoViewModel.ImagemUpload != null)
            {
                var prefixo = Guid.NewGuid().ToString() + "_";

                if(!await UploadImagem(produtoViewModel.ImagemUpload, prefixo))
                {
                    return View(produtoViewModel);
                }

                produtoAtualizacao.Imagem = $"{prefixo}{produtoViewModel.ImagemUpload.FileName}";
            }

            produtoAtualizacao.Nome = produtoViewModel.Nome;
            produtoAtualizacao.Descricao = produtoViewModel.Descricao;
            produtoAtualizacao.Valor = produtoViewModel.Valor;
            produtoAtualizacao.Ativo = produtoViewModel.Ativo;

            await _produtoService.Atualizar(_mapper.Map<Produto>(produtoAtualizacao));

            if(!OperacaoValida()) return View(produtoViewModel);

            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Produto", "Excluir")]
        [Route("excluir-produto/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var produtoViewModel = await ObterProduto(id);

            if(produtoViewModel == null)
                return NotFound();

            return View(produtoViewModel);
        }

        [ClaimsAuthorize("Produto", "Excluir")]
        [Route("excluir-produto/{id:guid}")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var produtoViewModel = await ObterProduto(id);

            if(produtoViewModel == null)
                return NotFound();

            await _produtoService.Remover(id);

            if(!OperacaoValida()) return View(produtoViewModel);

            return RedirectToAction(nameof(Index));
        }

        private async Task<ProdutoViewModel> ObterProduto(Guid fornecedorId)
        {
            var produto = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterProdutoFornecedor(fornecedorId));
            produto.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());
            return produto;
        }

        private async Task<ProdutoViewModel> PopularFornecedores(ProdutoViewModel produto)
        {
            produto.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());
            return produto;
        }

        private async Task<bool> UploadImagem(IFormFile imagemUpload, string prefixo)
        {
            if(imagemUpload.Length <= 0 || imagemUpload ==null) return false;

            var path = Path.Combine($@"{Directory.GetCurrentDirectory()}\wwwroot\imagens\{prefixo}{imagemUpload.FileName}");

            if(System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "Nome do arquivo já existe");
                return false;
            }

            using(var fs = new FileStream(path, FileMode.Create))
            {
                await imagemUpload.CopyToAsync(fs);
            }

            return true;
        }
    }
}

src/DevMS.App/Extensions/SummaryViewComponent.cs
using DevMS.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DevMS.App.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotificador _notificador;

        public SummaryViewComponent(INotificador notificador)
        {
            _notificador = notificador;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notificador.ObterNotificacoes());

            notificacoes.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x.Mensagem));

            return View();
        }
    }
}

src/DevMS.App/Views/Produtos/Create.cshtml
@model DevMS.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Novo Produto";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-9">
        <form enctype="multipart/form-data" asp-action="Create">

            @await Component.InvokeAsync("Summary")

            <div class="form-group">
                <label asp-for="FornecedorId" class="control-label"></label>
                <select asp-for="FornecedorId" class="form-control" asp-items="@(new SelectList(Model.Fornecedores, "Id", "Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="FornecedorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagemUpload" class="control-label"></label>

                <div class="input-group">
                    <label data-browse="Procurar"  class="custom-file-label" for="ImagemUpload"></label>
                    <input type="file" class="form-control" id="ImagemUpload" asp-for="ImagemUpload" />
                </div>
                    <label style="display:none" id="img_nome"></label>

                <span asp-validation-for="ImagemUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
        <script>
            $("#ImagemUpload").change(function(){
                $("#img_nome").text(this.files[0].name);
                $("#img_nome")[0].style.display = 'block';
            });

        $("#ImagemUpload").attr("data-val", "true");
        $("#ImagemUpload").attr("data-val-required", "Preencha o campo Imagem");
        </script>
}

src/DevMS.App/Views/Produtos/Delete.cshtml
@model DevMS.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Excluir " + Model.Nome;
}

<h1>@ViewData["Title"]</h1>

<h3>Você tem certeza disso?</h3>
<div class="row">
    <hr />
    <div class="col-md-4">
        <img style="width:400px" src="~/imagens/@Model.Imagem" alt="~/imagens/@Model.Imagem" />
    </div>
    <dl class="col-md-6">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FornecedorId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fornecedor.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Model.Valor.ToString("C")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" />
        <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
    </form>
</div>

src/DevMS.App/Views/Produtos/Details.cshtml
@model DevMS.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Detalhes " + Model.Nome;
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <hr />
    <div class="col-md-4">
        <img style="width:400px" src="~/imagens/@Model.Imagem" alt="~/imagens/@Model.Imagem" />
    </div>
    <dl class=" col-md-6">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FornecedorId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fornecedor.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Model.Valor.ToString("C")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a>
    <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
</div>

src/DevMS.App/Views/Produtos/Edit.cshtml
@model DevMS.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Editar " + Model.Nome;
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-10">
        <form enctype="multipart/form-data" asp-action="Edit">
            @await Component.InvokeAsync("Summary")

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Imagem Atual</label> <br/>
                <img src="~/imagens/@Model.Imagem" alt="~/imagens/@Model.Imagem" width="70px"/>
            </div>
            <div class="form-group">
                <label asp-for="ImagemUpload" class="control-label"></label>

                <div class="input-group">
                    <label data-browse="Procurar" class="custom-file-label" for="ImagemUpload"></label>
                    <input type="file" class="form-control" id="ImagemUpload" asp-for="ImagemUpload" />
                </div>
                <label style="display:none" id="img_nome"></label>
            </div>

            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $("#ImagemUpload").change(function () {
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });
    </script>
}

src/DevMS.App/Views/Produtos/Index.cshtml
@model IEnumerable<DevMS.App.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Produtos";
}

<h1>@ViewData["Title"]</h1>

@await Component.InvokeAsync("Summary")

<p>
    <a class="btn btn-info" asp-action="Create">Novo Produto</a>
</p>

<partial name="_DetalhesProduto" />

src/DevMS.App/Views/Produtos/_DetalhesProduto.cshtml
@model IEnumerable<DevMS.App.ViewModels.ProdutoViewModel>

<table class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th>
                <label>Imagem</label>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fornecedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    <img style="width:80px" src="~/imagens/@item.Imagem" alt="@item.Imagem" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fornecedor.Nome)
                </td>
                <td>
                    @item.Valor.ToString("C")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td class="text-end">
                    <a class="btn btn-info" asp-controller="Produtos" asp-action="Details" asp-route-id="@item.Id"><span class="fa fa-search"></span></a>
                    <a class="btn btn-warning" asp-controller="Produtos" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-pencil-alt"></span></a>
                    <a class="btn btn-danger" asp-controller="Produtos" asp-action="Delete" asp-route-id="@item.Id"><span class="fa fa-trash"></span></a>
                </td>
            </tr>
        }
    </tbody>
</table>